server:
  port: 8084

spring:
  application:
    name: embedding-service

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: embedding-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      enable-auto-commit: false

      properties:
        spring.json.trusted.packages: "*"

    listener:
      ack-mode: RECORD
