server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aiassistant
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update   # or validate/create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: embedding-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      enable-auto-commit: false

      properties:
        spring.json.trusted.packages: "*"

    listener:
      ack-mode: RECORD

document:
  storage:
    base-path: F:/AI-Powered-Knowledge-Assistant/document-service
